### ISSUE TITLE
eslint-disable with no rules appears empty on the dashboard

### ISSUE THREAD

**Issue by tniezurawski** [mansona/lint-to-the-future-eslint#14]
I found that a comment disabling ESLint for a file without specifying rules, appears without a name on the dashboard:

![image](https://user-images.githubusercontent.com/4335166/209876219-67bb3b73-fbc4-4a3e-9edd-a551e50b27ac.png)

This is the type of comment that makes "trouble":

```js
/* eslint-disable */
```

I'm not sure what's the desired behavior. Either you should filter it out from the results or treat it as some special case like "All rules disabled for a file". Not sure what fits better to lint-to-the-future philosophy 🙂

**Comment by mansona** [comment]
So I added a test that I thought was going to fail but it doesn't seem to recreate the issue 🤔 maybe we accidentally fixed this at some point? can you verify that you still have this issue in the latest release? 

see for the recreation https://github.com/mansona/lint-to-the-future-eslint/pull/32 let me know if it doesn't actually cover the use case correctly

**Comment by mansona** [comment]
I merged the test so let me know if it's still an issue and I can update the test 👍

**Comment by tniezurawski** [comment]
I no longer have empty `/* eslint-disable */` in the code, which was a mistake in the first place 😅 Let's assume it's fixed. Especially that you have a test for that 💪 Worst case scenario someone will find this issue and inform us that it still happens.
