### ISSUE TITLE
Option to include warnings

### ISSUE THREAD

**Issue by larrifax** [mansona/lint-to-the-future-eslint#15]
Would it be possible to add an option to include warnings when running `lint-to-the-future ignore`?
I'm using [eslint-plugin-only-warn](https://www.npmjs.com/package/eslint-plugin-only-warn), which makes it hard to use lint-to-the-future at this point..

**Comment by mansona** [comment]
So I'm not exactly familiar with that plugin but it looks like it's taking a different approach to dealing with large numbers of existing errors.

I would recommend trying to remove that plugin, run `lint-to-the-future ignore` and see if switching from `eslint-plugin-only-warn` to Lint to the Future is a viable option

**Comment by mansona** [comment]
I'm closing this for now because of a lack of response, please let me know if you want me to open it again 👍
